name: Build, test and deploy ASP.Net Core app to Azure Web App - freelancer-hub-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_STORAGE_CONNECTIONSTRING: ${{ secrets.AZURE_STORAGE_CONNECTIONSTRING }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_ORG: "Felipe Beppler Huller"
  SONAR_PROJECT_KEY: "freelancer-hub-backend"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install global tools
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global coverlet.console

      # Restore
      - name: Restore backend
        run: dotnet restore ./back-end/freelancer-hub-backend/freelancer-hub-backend.csproj

      - name: Restore tests
        run: dotnet restore ./back-end/freelancer-hub-backend-tests/freelancer-hub-backend-tests.csproj

      # Begin SonarCloud Analysis
      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"${{ env.SONAR_PROJECT_KEY }}" \
            /o:"${{ env.SONAR_ORG }}" \
            /d:sonar.login="${{ env.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="coverage.xml" \
            /d:sonar.host.url="https://sonarcloud.io"

      # Build backend
      - name: Build backend
        run: dotnet build ./back-end/freelancer-hub-backend/freelancer-hub-backend.csproj --no-incremental

      # Run tests and generate coverage
      - name: Run tests and generate coverage
        run: |
          coverlet ./back-end/freelancer-hub-backend-tests/bin/Debug/net8.0/freelancer-hub-backend-tests.dll \
            --target "dotnet" \
            --targetargs "test ./back-end/freelancer-hub-backend-tests/freelancer-hub-backend-tests.csproj --no-build" \
            -f opencover \
            -o "coverage.xml"

      # End SonarCloud Analysis
      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

      # Publish backend
      - name: Publish backend
        run: dotnet publish ./back-end/freelancer-hub-backend/freelancer-hub-backend.csproj -c Release -o "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_128C7F96EAC3414CA14721AC85B9886F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0BDA7162115F4343A59EF69D3C06C90A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E8D4DE4A215D444F81DC912C92525AA4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'freelancer-hub-backend'
          slot-name: 'Production'
          package: .
